version: '3.8'

services:
  app:
    restart: always
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: >
        sh -c "
        chmod +x ./wait-for-it.sh
        && ./wait-for-it.sh postgres_db:5432
        && uvicorn main:server --host 0.0.0.0 --port 8000"

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "blos"
      POSTGRES_PASSWORD: "close"
      POSTGRES_DB: "kda_hack"
    ports:
      - "5434:5432"