apiVersion: v1
kind: Service
metadata:
  name: hack-frontend-service
  labels:
    app: hack-frontend
spec:
  ports:
    - name: front-web
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: hack-frontend
  type: ClusterIP
